import { useState, useRef, useEffect } from 'react';
import { LayoutGrid, Users, CreditCard, Settings, UserCircle, LogOut, ChevronDown, BarChart3 } from 'lucide-react';
import logo from '../assets/svr-logo.jpeg';
import type { Page, OwnerAccount, AppUser } from '@/types';

interface Props { page: Page; setPage: (p: Page) => void; owner: OwnerAccount; user: AppUser; onLogout: () => void; children: React.ReactNode; }
const NAV_ITEMS: { id: Page; label: string; icon: React.ComponentType<{className?: string}>; admin?: boolean }[] = [
 {id:'rooms',label:'Room Chart',icon:LayoutGrid}, {id:'residents',label:'PG Residents',icon:Users}, {id:'payments',label:'Payments',icon:CreditCard,admin:true}, {id:'revenue',label:'Revenue',icon:BarChart3,admin:true}, {id:'settings',label:'Settings',icon:Settings,admin:true},
];
export default function DashboardLayout({page,setPage,owner,user,onLogout,children}: Props) {
 const [menuOpen,setMenuOpen]=useState(false); const menuRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const f=(e:MouseEvent)=>{if(menuRef.current&&!menuRef.current.contains(e.target as Node))setMenuOpen(false)};document.addEventListener('mousedown',f);return()=>document.removeEventListener('mousedown',f)},[]);
 const items=NAV_ITEMS.filter(i=>!i.admin||user.role==='ADMIN');
 return <div className="relative min-h-screen overflow-hidden bg-navy-900 text-white"><img src={logo} alt="" aria-hidden="true" className="pointer-events-none fixed left-1/2 top-1/2 z-0 w-[min(75vw,52rem)] -translate-x-1/2 -translate-y-1/2 opacity-[0.045] grayscale mix-blend-screen"/><header className="sticky top-0 z-50 glass-dark border-b border-navy-700"><div className="max-w-7xl mx-auto px-4 lg:px-8"><div className="flex items-center justify-between h-16"><div className="flex items-center gap-3"><img src={logo} alt="SVR logo" className="w-12 h-12 rounded-xl object-contain bg-black/20 p-1"/><div className="hidden sm:block"><p className="font-display font-bold text-lg leading-none">{owner.pgName}</p><p className="text-navy-300 text-xs mt-0.5">{user.role} • PG Management</p></div></div><nav className="hidden md:flex items-center gap-1">{items.map(i=><button key={i.id} onClick={()=>setPage(i.id)} className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium ${page===i.id?'bg-gold-400/15 text-gold-300 border border-gold-400/20':'text-navy-200 hover:bg-navy-700/50'}`}><i.icon className="w-4 h-4"/>{i.label}</button>)}</nav><div className="relative" ref={menuRef}><button onClick={()=>setMenuOpen(!menuOpen)} className="flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-navy-700/50"><div className="w-9 h-9 rounded-full bg-navy-700 flex items-center justify-center border border-gold-400/30"><UserCircle className="w-5 h-5 text-gold-400"/></div><span className="hidden sm:block text-sm">{user.username}</span><ChevronDown className="w-4 h-4"/></button>{menuOpen&&<div className="absolute right-0 mt-2 w-48 glass-dark rounded-xl border border-navy-600 shadow-2xl p-1"><button onClick={()=>{setPage('profile');setMenuOpen(false)}} className="w-full text-left px-3 py-2.5 rounded-lg text-sm hover:bg-navy-700/50">Owner Profile</button><button onClick={onLogout} className="w-full flex gap-3 px-3 py-2.5 rounded-lg text-sm text-red-300 hover:bg-red-500/10"><LogOut className="w-4 h-4"/>Logout</button></div>}</div></div><nav className="md:hidden flex items-center gap-1 overflow-x-auto pb-3">{items.map(i=><button key={i.id} onClick={()=>setPage(i.id)} className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm whitespace-nowrap text-navy-200"><i.icon className="w-4 h-4"/>{i.label}</button>)}</nav></div></header><main className="relative z-10 max-w-7xl mx-auto px-4 lg:px-8 py-8">{children}</main></div>;
}
