import { useMemo, useState } from 'react';
import { BarChart3, Download, FileSpreadsheet, FileText, IndianRupee } from 'lucide-react';
import type { PGData, PaymentStatus } from '@/types';

interface Props { data: PGData }
interface Row { name: string; room: string; mobile: string; rent: number; paid: number; pending: number; status: PaymentStatus; paymentDate: string; dueDate: string; createdDate: string; createdBy: string }
const money=(n:number)=>`₹${n.toLocaleString('en-IN')}`;
function csvCell(value: unknown){const s=String(value ?? ''); return /[",\n]/.test(s) ? `"${s.replace(/"/g,'""')}"` : s;}
export default function RevenuePage({data}: Props){
 const [status,setStatus]=useState<'all'|PaymentStatus>('all'); const [room,setRoom]=useState('all'); const [customer,setCustomer]=useState(''); const [month,setMonth]=useState('');
 const rows=useMemo<Row[]>(()=>data.residents.map(r=>{const rm=data.rooms.find(x=>x.id===r.roomId); const payment=data.payments.filter(p=>p.residentId===r.id).slice(-1)[0]; return {name:r.name,room:rm?.number||payment?.roomNumber||'',mobile:r.mobile,rent:r.rent,paid:r.paid,pending:Math.max(r.balance,0),status:r.paymentStatus,paymentDate:payment?.date||'',dueDate:payment?.dueDate||'',createdDate:r.createdAt||r.startDate,createdBy:r.createdBy||'System'};}).filter(r=>(status==='all'||r.status===status)&&(room==='all'||r.room===room)&&(!customer||r.name.toLowerCase().includes(customer.toLowerCase()))&&(!month||r.paymentDate.startsWith(month))),[data,status,room,customer,month]);
 const totals=rows.reduce((a,r)=>({revenue:a.revenue+r.rent,paid:a.paid+r.paid,pending:a.pending+r.pending,overdue:a.overdue+(r.status==='overdue'?r.pending:0)}),{revenue:0,paid:0,pending:0,overdue:0});
 const exportRows=rows.map(r=>({'Customer Name':r.name,'Room Number':r.room,Mobile:r.mobile,'Rent Amount':r.rent,'Paid Amount':r.paid,'Pending Amount':r.pending,'Payment Status':r.status,'Payment Date':r.paymentDate,'Due Date':r.dueDate,'Created Date':r.createdDate,'Created By':r.createdBy}));
 function download(name:string,content:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
 function csv(){const keys=Object.keys(exportRows[0]||{'Customer Name':''});download(`SVR_Revenue_Report_${new Date().toISOString().slice(0,10)}.csv`,[keys.join(','),...exportRows.map(r=>keys.map(k=>csvCell(r[k as keyof typeof r])).join(','))].join('\n'),'text/csv;charset=utf-8')}
 function excel(){const keys=Object.keys(exportRows[0]||{'Customer Name':''}); const table=`<table><tr>${keys.map(k=>`<th>${k}</th>`).join('')}</tr>${exportRows.map(r=>`<tr>${keys.map(k=>`<td>${csvCell(r[k as keyof typeof r])}</td>`).join('')}</tr>`).join('')}</table>`;download(`SVR_Revenue_Report_${new Date().toISOString().slice(0,10)}.xls`,table,'application/vnd.ms-excel')}
 function pdf(){const w=window.open('','_blank'); if(!w)return; w.document.write(`<html><head><title>SVR_Revenue_Report</title><style>body{font-family:Arial;padding:24px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #aaa;padding:6px;text-align:left}h1{color:#172b4d}</style></head><body><h1>SVR CO-LIVING PG</h1><h2>REVENUE REPORT</h2><p>Report date: ${new Date().toLocaleDateString('en-IN')}</p><p>Total Revenue: ${money(totals.revenue)} | Paid: ${money(totals.paid)} | Pending: ${money(totals.pending)} | Overdue: ${money(totals.overdue)}</p>${document.querySelector('[data-revenue-table]')?.outerHTML||''}</body></html>`);w.document.close();w.print();}
 return <div className="animate-fade-in"><div className="flex items-center justify-between mb-6"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-gold-400/10 flex items-center justify-center"><BarChart3 className="w-5 h-5 text-gold-400"/></div><div><h1 className="font-display font-bold text-2xl">Revenue</h1><p className="text-navy-300 text-sm">Admin revenue and payment report</p></div></div><div className="flex flex-wrap gap-2"><button onClick={excel} className="action"><FileSpreadsheet className="w-4 h-4"/>Export Excel</button><button onClick={csv} className="action"><Download className="w-4 h-4"/>Export CSV</button><button onClick={pdf} className="action"><FileText className="w-4 h-4"/>Export PDF</button></div></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">{[['Total Revenue',totals.revenue],['Paid',totals.paid],['Pending',totals.pending],['Overdue',totals.overdue]].map(([l,v])=><div className="glass-dark rounded-xl border border-navy-700 p-4" key={String(l)}><p className="text-navy-300 text-xs">{l}</p><p className="font-display font-bold text-xl flex items-center"><IndianRupee className="w-4 h-4"/>{Number(v).toLocaleString('en-IN')}</p></div>)}</div><div className="glass-dark rounded-xl border border-navy-700 p-4 mb-6 flex flex-wrap gap-3"><input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Customer" className="filter"/><select value={status} onChange={e=>setStatus(e.target.value as 'all'|PaymentStatus)} className="filter"><option value="all">All statuses</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="overdue">Overdue</option></select><select value={room} onChange={e=>setRoom(e.target.value)} className="filter"><option value="all">All rooms</option>{data.rooms.map(r=><option key={r.id} value={r.number}>{r.number}</option>)}</select><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="filter"/></div><div data-revenue-table className="overflow-x-auto glass-dark rounded-xl border border-navy-700"><table className="w-full text-sm"><thead><tr className="text-left text-navy-300 border-b border-navy-700">{['Customer','Room','Rent','Paid','Pending','Status','Payment Date','Due Date'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-b border-navy-800" key={`${r.name}-${r.room}-${r.createdDate}`}><td className="p-3">{r.name}</td><td className="p-3">{r.room}</td><td className="p-3">{money(r.rent)}</td><td className="p-3">{money(r.paid)}</td><td className="p-3">{money(r.pending)}</td><td className="p-3 uppercase">{r.status}</td><td className="p-3">{r.paymentDate}</td><td className="p-3">{r.dueDate}</td></tr>)}</tbody></table></div></div>;
}
