import { useState, useEffect, useCallback } from 'react';
import AuthPage from '@/components/AuthPage'; import DashboardLayout from '@/components/DashboardLayout'; import RoomChart from '@/components/RoomChart'; import ResidentsPage from '@/components/ResidentsPage'; import PaymentsPage from '@/components/PaymentsPage'; import SettingsPage from '@/components/SettingsPage'; import OwnerProfilePage from '@/components/OwnerProfilePage'; import RevenuePage from '@/components/RevenuePage';
import type { Page, OwnerAccount, PGData, AppUser } from '@/types'; import { getOwnerAccount, getOwnerSession, clearOwnerSession, getPGData, savePGData } from '@/lib/storage'; import { clearAuth, getCurrentUser } from '@/lib/auth';
export default function App(){const [loggedIn,setLoggedIn]=useState(false);const [owner,setOwner]=useState<OwnerAccount|null>(null);const [user,setUser]=useState<AppUser|null>(null);const [page,setPage]=useState<Page>('rooms');const [pgData,setPgData]=useState<PGData|null>(null);const [booted,setBooted]=useState(false);
 useEffect(()=>{const session=getOwnerSession(),account=getOwnerAccount(),current=getCurrentUser();if(session.loggedIn&&account&&current){setLoggedIn(true);setOwner(account);setUser(current)}setPgData(getPGData());setBooted(true)},[]);
 const login=useCallback(()=>{const current=getCurrentUser();const account=getOwnerAccount();if(current){setUser(current);setOwner(account);setLoggedIn(true);setPage('rooms')}},[]); const logout=useCallback(()=>{clearAuth();clearOwnerSession();setLoggedIn(false);setOwner(null);setUser(null);setPage('rooms')},[]); const update=useCallback((d:PGData)=>{savePGData(d);setPgData(d)},[]);
 if(!booted)return <div className="min-h-screen bg-navy-900 flex items-center justify-center"><div className="w-8 h-8 border-2 border-gold-400 border-t-transparent rounded-full animate-spin"/></div>; if(!loggedIn||!owner||!pgData||!user)return <AuthPage onLogin={login}/>;
 const safePage = user.role==='CUSTOMER' && ['payments','revenue','settings','profile'].includes(page) ? 'rooms' : page; if(safePage!==page)setPage(safePage);
 return <DashboardLayout page={safePage} setPage={setPage} owner={owner} user={user} onLogout={logout}>{safePage==='rooms'&&<RoomChart data={pgData} setData={update}/>} {safePage==='residents'&&<ResidentsPage data={pgData} setData={update}/>} {safePage==='payments'&&user.role==='ADMIN'&&<PaymentsPage data={pgData} setData={update}/>} {safePage==='revenue'&&user.role==='ADMIN'&&<RevenuePage data={pgData}/>} {safePage==='settings'&&user.role==='ADMIN'&&<SettingsPage data={pgData} setData={update} onOwnerReset={logout}/>} {safePage==='profile'&&user.role==='ADMIN'&&<OwnerProfilePage owner={owner} setOwner={setOwner}/>}</DashboardLayout>;
}
